name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore

    - name: Create Release
      # You may pin to the exact commit or the version.
      # uses: ncipollo/release-action@7c5046364401a3e122086927d07617a3d756b658
      uses: ncipollo/release-action@v1.8.4
      with:
        artifacts: NPS/*
        name: NPSBrowser
        tag: day${{ env.DATE }}
        token: ${{ secrets.GITHUB_TOKEN }}
